name: Pre-commit autoupdate

on:
  schedule:
    - cron: "20 03 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: 3.11

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate

      - name: Check for changes
        id: git-diff
        run: echo "changed=$(git diff --exit-code || echo 'true')" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        if: steps.git-diff.outputs.changed == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b chore/update-pre-commit-hooks
          git add .
          git commit -m "chore: update pre-commit hooks"
          gh pr create --title "chore: update pre-commit hooks" --body "Updates pre-commit hooks to the latest versions." --base main --label dependencies --label pre-commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
