name: Pre-commit autoupdate

on:
  schedule:
    - cron: "20 03 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate

      - name: Check for changes
        id: git-diff
        run: echo "::set-output name=changed::$(git diff --exit-code || echo 'true')"

      - name: Create Pull Request
        if: steps.git-diff.outputs.changed == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b chore/update-pre-commit-hooks
          git add .
          git commit -m "chore: update pre-commit hooks"
          gh pr create --title "chore: update pre-commit hooks" --body "Updates pre-commit hooks to the latest versions." --base main --label dependencies --label pre-commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
